### ISSUE TITLE
Demo importer tab is not showing up 

### ISSUE THREAD

**Issue by cbcbr** [Webcreations907/WBC-Importer-extension#10]
Hey,

I added redux 3.5 as a plugin in a new theme, but demo importer tab is not showing up. I did this in other themes without problems, the importer extension works perfect. But I can not figure out, why the tab is not showing up in this one. I deactivated all plugins, the demo tab is still missing. Everything else is fine, theme options are fine, too. A test with former redux versions have the same result. So I am not sure, if this is a redux error or a theme issue, since themecheck reports no error and the build in redux theme options importer works.
Can you help?

Thanks.

**Comment by Webcreations907** [comment]
Hello,

Do you have the importer ext in the theme or the plugin?

**Comment by cbcbr** [comment]
Hi,

I tried both, I have it ext in the theme now.

Thanks

**Comment by cbcbr** [comment]
Hi,

maybe this helps:
I made a test with another theme and a working importer. After a redux update to 3.5.x, the tab went away. Then I reverted redux back to version 3.4.1 and the tab came back, the importer works fine again. I tried the same on the new theme and now the demo importer tab is there (Latest Importer, Redux 3.4.1, Wordpress 4.1.1). Same on theme integration and plugin version.

**Comment by Webcreations907** [comment]
I've tested and unable to reproduce that issue, can you send me you theme/setup? Or is it online where I can test that? 

Also did you make sure to rename the `Redux_Framework_sample_config` class in your Redux config file?

If you can send, send to webcreations907@gmail.com 

Thanks

**Comment by Webcreations907** [comment]
Hey there,

I just put up a test theme which includes ReduxFramework 3.5 and the latest WBC_importer, give it a try and see if the demo importer shows up for you if you're still having issues

https://github.com/Webcreations907/underscores-redux

**Comment by cbcbr** [comment]
Hey,
demo importer shows up on 3.5, all good now. Thanks, Great Work!

**Comment by cbcbr** [comment]
Mark as done :)
