### ISSUE TITLE
Help with installation

### ISSUE THREAD

**Issue by MargieinAZ** [Webcreations907/WBC-Importer-extension#11]
Hi, I've been trying to install this for several hours and I'm not having much success yet, the tab is not showing up for me.
I altered the loader.php file within the admin/redux-extensions folder as follows:

 // Modify {$redux_opt_name} to match your opt_name
    add_action("redux/extensions/my_theme/before", 'my_theme_register_custom_extension_loader', 0);
endif;

---

And I altered my functions.php file as follows:

/**
- Add Redux Framework & extras
  */
  require_once( dirname( **FILE** ) . '/admin/redux-extensions/loader.php' );
  require get_template_directory() . '/admin/admin-init.php';
  ------------------------------------------------

And I dropped the "wbc_importer" folder into the "admin/redux-extensions/extensions" folder.

---

But the tab is not showing up in my theme options panel.

Any suggestions? I'm sure I'm missing something obvious. Just can't figure out what it is.

I'm running Redux Framework v3.5.0, and WP  Version 4.1.1 

Thanks,
-Margie

**Comment by Webcreations907** [comment]
Hello,

Do you have Redux installed as plugin or embedded in theme?

**Comment by MargieinAZ** [comment]
I have it set up as both. Through their "suggest and embed" option:

"Suggest + Embed: Redux is embedded, but also a TGM recommendation is given to install the plugin. The plugin overrides the embedded code."

**Comment by MargieinAZ** [comment]
FYI, I just removed it as a plugin, and updated the embedded version of Redux, on the chance that the plugin was causing an issue. Still no luck.

**Comment by Webcreations907** [comment]
Are you able to provide access to theme or send it to me to test? I've tried and unable to reproduce that issue.

**Comment by Webcreations907** [comment]
I just put up a test theme which includes ReduxFramework 3.5 and the latest WBC_importer, give it a try and see if the demo importer shows up for you.

https://github.com/Webcreations907/underscores-redux

**Comment by MargieinAZ** [comment]
Thank you! I was able to get it to show up now. Not sure why it wasn't working in the first place, but it's showing up now.
Thanks!

Now I 'm running into errors trying to import the data:

Fatal error:  Allowed memory size of 67108864 bytes exhausted (tried to allocate 72 bytes) 

That's a different issue, so I'll do some more research into why I'm getting that, but if you have a link or a quick insight into how to resolve that, I'd really appreciate it.

Thaks again!!!

**Comment by Webcreations907** [comment]
No problem, glad that worked out for you. If you're using that demo theme as example you'd just drop any extensions into the extensions folder and they get loaded. Forgot to mention that, if you happen to get any of Redux's premium extensions.

As for the memory, you should try increasing memory. You can do this by .htaccess file or if you have access to the php.ini file you can change it there. See link below and scroll down to the section "Increasing the PHP Memory Limit" where you'll see the examples for .htaccess and php.ini changes.

http://code.tutsplus.com/tutorials/fixing-the-wordpress-white-screen-of-death--cms-21008

Hope that helps :smile:
