### ISSUE TITLE
Can I install Wordpress Options with WBC-Importer-extension Script?

### ISSUE THREAD

**Issue by kidesigner** [Webcreations907/WBC-Importer-extension#12]
Can I install Wordpress Options with WBC-Importer-extension Script?

**Comment by Webcreations907** [comment]
Hello,

Are you referring to a plugin, or the theme options?

**Comment by kidesigner** [comment]
I use for theme options. Thank

**Comment by Webcreations907** [comment]
It works for importing redux theme options if that's what you're referring to.

Imports by default, theme options, widgets, and demo data. If you check the `example-functions.php` file there is a block of code at the bottom that shows how to import Revolutions slider, set menus, and set home page.

**Comment by kidesigner** [comment]
Thank you for support, it's working!

**Comment by Webcreations907** [comment]
That's great, glad it worked out for you!

Anything else, just let me know.

Thanks
