### ISSUE TITLE
Why home page need to select?

### ISSUE THREAD

**Issue by jahir07** [Webcreations907/WBC-Importer-extension#13]
Hi,

Extension working fine. But after import i have to select page template from settings >> reading. I want home page template with all settings. How can i fix that.. 

Thanks

**Comment by Webcreations907** [comment]
Hello,

You need to set your homepage using action/function, check the example-functions.php file. There is a block of code/example in there for how to set your menu, homepage, etc. 

https://github.com/Webcreations907/WBC-Importer-extension/blob/master/example-functions.php#L205-L285

:smile:

**Comment by jahir07** [comment]
woow.. thanks..

**Comment by jahir07** [comment]
thanks works fine.. but rev slider import option not working.. here is the code--

if ( class_exists( 'RevSlider' ) ) {
            //If it's demo3 or demo5
            $wbc_sliders_array = array(
                'demo1' => get_template_directory_uri(). '/sample_rev.zip', //Set slider zip name
                'demo5' => 'anotherslider.zip', //Set slider zip name
            );
            if ( isset( $demo_active_import[$current_key]['directory'] ) && !empty( $demo_active_import[$current_key]['directory'] ) && array_key_exists( $demo_active_import[$current_key]['directory'], $wbc_sliders_array ) ) {
                $wbc_slider_import = $wbc_sliders_array[$demo_active_import[$current_key]['directory']];
                if ( file_exists( $demo_directory_path.$wbc_slider_import ) ) {
                    $slider = new RevSlider();
                    $slider->importSliderFromPost( true, true, $demo_directory_path.$wbc_slider_import );
                }
            }
        }

can you please help to import rev slider also..

**Comment by Webcreations907** [comment]
You only need to enter the name of the zip like `sample_rev.zip` in that array, then make sure that your zip file is in the demo folder for the demo it goes to. 

That array should look like below.

```
$wbc_sliders_array = array(
'demo1' => 'sample_rev.zip', 
'demo5' => 'anotherslider.zip', 
);
```

**Comment by jahir07** [comment]
thanks.. lets try..

**Comment by Webcreations907** [comment]
No problem, did you get that working?

**Comment by jahir07** [comment]
thanks.. its working.. :)

**Comment by Webcreations907** [comment]
Great, thanks for letting me know and closing out issue. 

:smile:
