### ISSUE TITLE
Not display loading when importing data in ReduxFramework 3.5.4

### ISSUE THREAD

**Issue by kidesigner** [Webcreations907/WBC-Importer-extension#17]
Not display loading when importing data in ReduxFramework 3.5.4. Please test it. Thank so much

**Comment by Webcreations907** [comment]
Hello,

Did you try the latest version of the wbc_importer? I made a commit yesterday that should have fixed that spinner/loading.. not show showing.

**Comment by kidesigner** [comment]
I try but seem it's not working.

**Comment by kidesigner** [comment]
Please update lastest wordpress version and lastest reduxframework version to check. Thank you so much, my friend

**Comment by Webcreations907** [comment]
Just tested again, and can see the loading... + spinner when importing. Have you tried clearing browser cache?

What browser are you using?

**Comment by kidesigner** [comment]
I use chrome

**Comment by Webcreations907** [comment]
Just tested in Chrome and Firefox seemed to work

**Comment by kidesigner** [comment]
Clear cache and it' working well. Thank you for rocket support!

**Comment by Webcreations907** [comment]
Hey that's great, glad you got that working. Notice any other issues just let me know.

Thanks :smile:
