### ISSUE TITLE
Problem with Menu Activation

### ISSUE THREAD

**Issue by asifsaho** [Webcreations907/WBC-Importer-extension#18]
Hi,

I reviewed the example functions to activate menu, set homepage and revolution slider. but can't understand how to activate the menu.

This is the codeblock for menu I think.

// If it's demo1 - demo6
        $wbc_menu_array = array( 'demo1', 'demo2', 'demo3', 'demo4', 'demo5', 'demo6' );
        if ( isset( $demo_active_import[$current_key]['directory'] ) && !empty( $demo_active_import[$current_key]['directory'] ) && in_array( $demo_active_import[$current_key]['directory'], $wbc_menu_array ) ) {
            $top_menu = get_term_by( 'name', 'Temp Menu', 'nav_menu' );
            if ( isset( $top_menu->term_id ) ) {
                set_theme_mod( 'nav_menu_locations', array(
                        'theme-primary' => $top_menu->term_id,
                        'theme-footer'  => $top_menu->term_id
                    )
                );
            }
        }

Now I have 3 menus registered,

'primary_navigation' => __('Primary Navigation', 'townhall'),
'common_navigation' => __('Common Navigation', 'townhall'),
'blog_secondary' => __('Blog Category Navigation', 'townhall'),

Now where I should change in that codeblock?
for suppose I have 3 menus already imported called
Blog Category Menu, Primary Menu and Inner Page Nav

Thank you

**Comment by Webcreations907** [comment]
Hello,

You'd need to change the locations, and where it says "Temp Menu"

Below is a example, you'll need to change `Menu Name Here` with the name of your menu that you created when creating the menu on the menus page of WordPress.

```
if ( isset( $demo_active_import[$current_key]['directory'] ) && !empty( $demo_active_import[$current_key]['directory'] ) && in_array( $demo_active_import[$current_key]['directory'], $wbc_menu_array ) ) {
    $primary_menu = get_term_by( 'name', 'Menu Name Here', 'nav_menu' );
    $common_menu = get_term_by( 'name', 'Menu Name Here', 'nav_menu' );
    $blog_menu = get_term_by( 'name', 'Menu Name Here', 'nav_menu' );
    if ( isset( $primary_menu->term_id ) && isset( $common_menu->term_id ) && isset( $blog_menu->term_id ) ) {
        set_theme_mod( 'nav_menu_locations', array(
                'primary_navigation' => $primary_menu->term_id,
                'common_navigation'  => $common_menu->term_id,
                'blog_secondary'     => $blog_menu->term_id,
            )
        );
    }
}
```
