### ISSUE TITLE
add_action add_filter not working on wordpress-importer.php

### ISSUE THREAD

**Issue by franmastromarino** [Webcreations907/WBC-Importer-extension#19]
hello, i have some custom fields in my wordpress menus, so i need to hook the importer process

for example im trying to hook in to the importer

add_action('import_end', 'lmm_import_save');

this works when i fire the importer from Tools > Import, but isn't working when it's fired from the redux panel

regards

**Comment by Webcreations907** [comment]
Hello,

Sorry for the delay back on this, hoping you got it working.

But I did take a look and seemed like it works and is being called. If you have a error somewhere maybe it's not getting that far before exiting.

You could check the console and see if it shows a error message during the importing.

**Comment by Webcreations907** [comment]
Hope you got this working, if not just let me know.

Thanks
