### ISSUE TITLE
Set homepage automaticly

### ISSUE THREAD

**Issue by goranefbl** [Webcreations907/WBC-Importer-extension#2]
Just a feature request, maybe possibility to also automatically set chosen page as homepage instead of going in settings and setting it up as home page. Its just updating wp_option with page_on_front option name and using page ID as value. And     update_option( 'show_on_front', 'page' ).

Do you know what would be the best way to do this. For example if we create txt file that would have page id in it, is there callback after successful import that could do this option update ?

Also i am releaseing theme on themeforest soon with importer in it, it looks really great, i am sure customers will love it.

**Comment by Webcreations907** [comment]
Hello,

I believe it already does what you're asking. In the example-functions.php there are actions and filters that can be used. Down at the bottom(see link below) there is a whole example of how to set homepage, menus, import Revolution slider, etc. 

https://github.com/Webcreations907/WBC-Importer-extension/blob/master/example-functions.php#L210

Check that out and let me know if that's what you were looking for. 

Glad you're liking the importer :smile:

**Comment by goranefbl** [comment]
Yay! 

Mark as done :)
