### ISSUE TITLE
Menu have bug with ReduxFramework 3.5.4  

### ISSUE THREAD

**Issue by kidesigner** [Webcreations907/WBC-Importer-extension#20]
All things running well, but i see bug menu in panel. Please see this:

http://i.imgur.com/BmadbfX.png

"Options Object" menu label. Please support me, thank you so much!

**Comment by zabestof** [comment]
That's not a bug from the importer. It seems the dev mode option of redux is now turned automatically on when you have WP_DEBUG set to true. If you set it to false that label will be gone.

Cheers!

**Comment by kidesigner** [comment]
Ok. It' working.
