### ISSUE TITLE
Default wordpress widget still display when import widget.

### ISSUE THREAD

**Issue by kidesigner** [Webcreations907/WBC-Importer-extension#21]
I see Default wordpress widget still display when import widget. (i was disabled it in my demo).

Please check. Thank you

**Comment by Webcreations907** [comment]
Hello,

Just tested and didn't set any widgets besides the ones in the widgets file. Make sure you didn't include the default widgets in your export file for you widgets.

**Comment by Webcreations907** [comment]
Going to mark this a solved, if you're still having issues just let me know.

Thanks
