### ISSUE TITLE
Theme-Check WARNING about filesystem operation

### ISSUE THREAD

**Issue by theKhorshed** [Webcreations907/WBC-Importer-extension#22]
Hi, the extension is working great but fixing these Theme-Check warning will be great. 
Here is a screenshot of the warning i am getting.

![screen shot 2015-07-02 at 2 13 41 pm](https://cloud.githubusercontent.com/assets/10390188/8472671/007470bc-20c5-11e5-82d9-c7f08905e931.png)

**Comment by Webcreations907** [comment]
Hello,

With the exception of line 236 and 338 in your screen image, the others are from the actual WordPress importer plugin. https://wordpress.org/plugins/wordpress-importer/
