### ISSUE TITLE
Need to access to array $this->field['wbc_demo_imports'] 

### ISSUE THREAD

**Issue by dimitrilongo** [Webcreations907/WBC-Importer-extension#25]
hi

Thank you so much for that extension, save me a lot of time, it works like a charm.

I have juste one question i need to acess to ReduxFramework_wbc_importer object outside the class, 
`print_r($this->field['wbc_demo_imports'] );`
I'd like to access that array in my redux in another section (tab).

Hope i'm clear.
Regards

**Comment by Webcreations907** [comment]
Could try with the below, but would have to be after redux class is started.

```
$wbc_importer_class = ReduxFramework_extension_wbc_importer::get_instance();
print_r($wbc_importer_class->wbc_import_files);
```

OR

replace YOUR_OPTION_NAME with your options name.

```
$example = apply_filters( "redux/YOUR_OPTION_NAME/field/wbc_importer_files", array(),10);
print_r($example);
```
