### ISSUE TITLE
Place the importer and demos in a plugin folder

### ISSUE THREAD

**Issue by grosscorporation** [Webcreations907/WBC-Importer-extension#3]
//redux options loader
//require_once get_template_directory() . '/inc/redx-ext/loader.php';

```
foreach ( glob( plugin_dir_path( __FILE__ ) . "plugin/redx-ext/loader.php" ) as $file ) {
    include_once $file;
}
```

it recognises but fails to load the content on the panel

**Comment by Webcreations907** [comment]
Hello,
Are you trying to put it in the Redux plugin or a custom plugin?

**Comment by grosscorporation** [comment]
a custom plugin that I have created for the theme

**Comment by Webcreations907** [comment]
Hey there,

Sorry for the delay back, been out sick for a bit.

I'm guessing you got this figured out as your other topic #4 seems like you're making progress on getting it going.

**Comment by grosscorporation** [comment]
sorry man, hope you good now

**Comment by Webcreations907** [comment]
Yes, thanks doing much better now. 

Will close this out, if you have further issues/questions just let me know.

Thanks
