### ISSUE TITLE
[Pull Request] Spinner not working after WP 4.2

### ISSUE THREAD

**Issue by ahmadawais** [Webcreations907/WBC-Importer-extension#31]
## Problem

After 4.2 update the spinner has stopped working. Which looks strange coz user doesn't wait for the demo to be imported and everything messes up
## Solved

Spinner was not working after WP 4.2 I have resolved the issue and sent three pull requests
## Pull requests

https://github.com/ahmadawais/WBC-Importer-extension/tree/patch-1
https://github.com/ahmadawais/WBC-Importer-extension/tree/patch-2
https://github.com/ahmadawais/WBC-Importer-extension/tree/patch-3

Kindly pull them.

**Comment by Webcreations907** [comment]
Hello,

Did you check with current version of the importer, there was a update for that back in April 2c1b30a94a24b5923f030fb9285474431b8abc3b

**Comment by ahmadawais** [comment]
@Webcreations907 Actually there were no releases so I figured there was no update.

**Comment by ahmadawais** [comment]
I just tested it and the update didn't work, so I am going ahead with my pull request. Must be something to do with visibility property.

**Comment by Webcreations907** [comment]
hmm, just tested on 3 different browsers with latest Redux and WP and didn't have any issues with the spinner on importing or re-importing.

Did you clear your browser cache/hard refresh after updating to the current version?
