### ISSUE TITLE
There was an error importing demo content

### ISSUE THREAD

**Issue by saschametz95** [Webcreations907/WBC-Importer-extension#33]
When I click on a Demo Import, this message appears after a while:
"There was an error importing demo content"

How do I know now what went wrong?

**Comment by Webcreations907** [comment]
Hello,

You can check the browser response in the console(firebug,etc) to see what the error message says.

**Comment by Webcreations907** [comment]
Hoping you got this figured out, going to close this issue. If you have further issues or questions just let me know.

Thanks
