### ISSUE TITLE
Importer not working on some servers

### ISSUE THREAD

**Issue by glmarco24** [Webcreations907/WBC-Importer-extension#34]
Hi,

Maybe someone had similar problem, importer is working in local, working on my servers, but some users complained it doesn't work. After my check and attempt to run importer on clean, new wp installation, it appears it's really not working on some servers.

Any idea what might be a problem?

Thanks!

**Comment by Webcreations907** [comment]
Are you updated to latest version? Some servers require FTP info, so there is a alternate way used in the latest version.

Also you can check the browser console(firebug,etc) to see if there is a error message, might be max file size upload limit as well.

**Comment by glmarco24** [comment]
Actually I found that on some server importing images is a problem. Looks like some server configuration issue, but I am not sure which one. I had an image as a first item and that stops everything. When I changed order posts, pages, categories, tags, etc. are imported without any problem.

**Comment by Webcreations907** [comment]
Happen to know if you have the same issue just using the normal WP importer?

**Comment by glmarco24** [comment]
Yes, yes! At the end I tried to use regular importer and there was a problem too. So, it's not related to WBC-Importer-extension

**Comment by Webcreations907** [comment]
That's odd, wish I had a way to replicate that issue but I haven't ran into it yet. Maybe when the WP importer updates, hopefully they'll fix that issue as well.
