### ISSUE TITLE
Is there a hook that could be used after import is done?

### ISSUE THREAD

**Issue by ahmadawais** [Webcreations907/WBC-Importer-extension#35]
I would like to automattically assing the menus and front/blog pages once the import is done. I can do that programatically but there should be a hook which I can use to trigger that code, since if there is no page called Home (before demo is imported) I cannot assign Home to Front page.

Is there a way around this? Any help would be really appreciated.

**Comment by Webcreations907** [comment]
Hello,
At the bottom of example-functions.php (link below) you'll find example on setting home page, menu, etc.

https://github.com/Webcreations907/WBC-Importer-extension/blob/master/example-functions.php#L205-L285

**Comment by Webcreations907** [comment]
Hoping you got this figured out, going to close this issue. If you have further issues or questions just let me know.

Thanks
