### ISSUE TITLE
it is not importing data file of redux theme options

### ISSUE THREAD

**Issue by pareshsojitra** [Webcreations907/WBC-Importer-extension#36]
hi

I'm not getting theme options imported redux theme options data file.
- widget & content.xml is successfully imported.

**Comment by Webcreations907** [comment]
Hello,

Hopefully you got this figured out. If not did you copy the theme options from the Redux import/export panel?

**Comment by wildrain** [comment]
I successfully imported redux option data and it shows in my theme front-end as well but when i click save changes button in redux option panel the redux data are gone. How can i fix this ?

**Comment by Webcreations907** [comment]
@wildrain it might be because the old values are still in the redux panel after import so if u click the save button it overwrites the imported settings. 

After import try refreshing the browser before clicking the save button and see if that resolves it

**Comment by pareshsojitra** [comment]
Hi,
It was a problem of refreshing the theme option page after import.

I've done this by refreshing the page.

**Comment by mtaddia** [comment]
hi,
i am using the importer and it imports the demo however, once it finishes and saves the settings - it says "saved" in green however the file is saved but it doesnt write to the external css file i am using with the compiler. If you change something AFTER the demo import like a text size, then click save THEN it writes to the css file and everything is fine after that. I tried refreshing and then saving again after the demo import test but again- the css file is not updated unless i physically change one of the settings then save again- kind of a wierd extra step for the theme i am developing - can u please tell me how to fix this?
