### ISSUE TITLE
Import demo issues

### ISSUE THREAD

**Issue by nomansbeauty** [Webcreations907/WBC-Importer-extension#37]
Hi,

Thanks for making this wonderful extension. But we noticed problems while using it since 8+ months. Sometimes it imports data and sometimes it breaks in the mid. Particularly updated version is not working on following hosts:
- GoDaddy
- Hostgator
- Localhost (previous version worked on this)

Hoping for you to please consider a solution for this and giving reasonable error messages to users is also a suggestion, in case anything breaks or give a log at end.

Thank you

**Comment by Webcreations907** [comment]
Hello,

Maybe file upload size? If you can check the browser console and see what the error message says.

**Comment by nomansbeauty** [comment]
Okay I will check browser console and see if anything shows up. Thanks for your reply.

**Comment by Webcreations907** [comment]
No problem, you'll see the ajax request when clicking the import button just toggle that open and check out the response.

**Comment by nomansbeauty** [comment]
Hi,
We tested again, and got this response in console:
<b>
Failed to load resource: the server responded with a status of 500 (Internal Server Error)
.../wp-admin/admin-ajax.php
</b>
Is it a data size issue? If yes, how can we extend / change this limit and timeout request of the script?
Thank you

**Comment by Webcreations907** [comment]
Hello,

Try increasing the max_execution_time and see if you still get the error, if you have fairly large demo content being imported it may be timing out.

**Comment by nomansbeauty** [comment]
max_execution_time = 400 seconds already and I think its sufficient enough. Cant plugin throw a relevant error message if it happens?

<b>Suggestions:</b>
1. Import data in form of chunks to avoid timeout issue. Customers dont like to change server settings before installing demo content. Some of them even got frustrated.
1. Show a relevant warning or error message for any such instances like network connect lost, memory limit reached, max execution time limit is exceeded during import, etc...

Its a really great script and I think we can improve it together.
Thank you
