### ISSUE TITLE
Would it be possible to do a Progress Bar instead of the Spinner?

### ISSUE THREAD

**Issue by contempoinc** [Webcreations907/WBC-Importer-extension#39]
How hard would it be to swap out the "who knows where the downloads at" spinner and replace it with a progress bar or numeral percentage? I find buyers on slower hosting are complaining "I started it 15 minutes ago and its still spinning, whats going on!?!" and assuming its broken.

Is something like that possible to do, would be 100% better for usability.

**Comment by Webcreations907** [comment]
Hello,

I'll see if I can get a progress bar figured out for it, think the main part of the time will be when downloading the demo images from servers.

**Comment by contempoinc** [comment]
Yup, that's exactly it. I've got a ton of nice high res images in my RE7 theme and that's where all the time is spent.

**Comment by Webcreations907** [comment]
Will try to get something together, have a few ideas for it so hopefully can get that up. Would you be willing to test it out if I put it in a dev branch?

**Comment by contempoinc** [comment]
Definitely up to beta test.

On Tuesday, September 1, 2015, Webcreations907 notifications@github.com
wrote:

> Will try to get something together, have a few ideas for it so hopefully
> can get that up. Would you be willing to test it out if I put it in a dev
> branch?
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/Webcreations907/WBC-Importer-extension/issues/39#issuecomment-136947523
> .

## 

Cheers,

Chris Robinson
www.contempoinc.com
twitter.com/contempoinc

**Comment by contempoinc** [comment]
Just had one buyer apparently super impatient, clicked the demo import 10x and nows he's got the content duplicated 10x all because he thought the "Spinning wheel of death"  he called it was hung.

**Comment by Webcreations907** [comment]
Shouldn't be able to re-click it while it's importing. Think the one thing that will duplicate also is the menus, was planning on looking into that as well, even though the default WP importer does it. 

Working on that progress bar now though.

**Comment by contempoinc** [comment]
Right, he actually killed the process and restarted. Yup, menus do
duplicate. Should be an easy check if menu exists, die. Lol maybe?

Awesome, looking forward to testing!

On Wednesday, September 2, 2015, Webcreations907 notifications@github.com
wrote:

> Shouldn't be able to re-click it while it's importing. Think the one thing
> that will duplicate also is the menus, was planning on looking into that as
> well, even though the default WP importer does it.
> 
> Working on that progress bar now though.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/Webcreations907/WBC-Importer-extension/issues/39#issuecomment-137268620
> .

## 

Cheers,

Chris Robinson
www.contempoinc.com
twitter.com/contempoinc

**Comment by Webcreations907** [comment]
Test out the importer from develop branch https://github.com/Webcreations907/WBC-Importer-extension/tree/develop and see how that works for you. 

I may change it a bit more, but least you can try that out :smile: 

EDITED TO ADD: you may have to test with actual demo content/image so that it takes longer to load to see it work.

**Comment by contempoinc** [comment]
Nice, I'll give it test in the morning! Do you have a quick screenshot of
it?

Cheers,

Chris Robinson
www.contempoinc.com
twitter.com/contempoinc

**Comment by Webcreations907** [comment]
Will look like the below, the spinner will still be there as well. The color of the progress bar is whatever the primary color for admin/profile is set to.

![progress-bar](https://cloud.githubusercontent.com/assets/8421576/9651830/02e8e4a8-51c2-11e5-900b-edcaf341a865.png)

**Comment by contempoinc** [comment]
That is looking rad man, will give it a try mañana!

On Wednesday, September 2, 2015, Webcreations907 notifications@github.com
wrote:

> Will look like the below, the spinner will still be there as well. The
> color of the progress bar is whatever the primary color for admin/profile
> is set to.
> 
> [image: progress-bar]
> https://cloud.githubusercontent.com/assets/8421576/9651830/02e8e4a8-51c2-11e5-900b-edcaf341a865.png
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/Webcreations907/WBC-Importer-extension/issues/39#issuecomment-137347967
> .

## 

Cheers,

Chris Robinson
www.contempoinc.com
twitter.com/contempoinc

**Comment by contempoinc** [comment]
I grabbed the development branch to test and I'm still seeing the ol' loading icon? http://cl.ly/image/452b1S1a0318

**Comment by contempoinc** [comment]
Grabbing it now to test.

**Comment by Webcreations907** [comment]
Did u clear browser cache?

**Comment by Webcreations907** [comment]
Let me know how that works out for you, I'll be making another quick change here in a bit, just to the JS files

**Comment by contempoinc** [comment]
Cleared cache and regrabbed the dev branch and still not seeing the progress bar, http://cl.ly/image/3W1D271k0Z1F?

**Comment by Webcreations907** [comment]
Will check it out. Are you testing locally?

**Comment by Webcreations907** [comment]
I just test the dev branch in Firefox and Chrome, seemed to work. 

Did you make sure to replace the extension_wbc_importer.php file as well?

**Comment by contempoinc** [comment]
I am working locally, I replaced/merged the entire directory save my demos.
I'll double check that file.

On Thursday, September 3, 2015, Webcreations907 notifications@github.com
wrote:

> I just tested the dev branch in Firefox and Chrome, seemed to work.
> 
> Did you make sure to replace the extension_wbc_importer.php file as well?
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/Webcreations907/WBC-Importer-extension/issues/39#issuecomment-137502460
> .

## 

Cheers,

Chris Robinson
www.contempoinc.com
twitter.com/contempoinc

**Comment by Webcreations907** [comment]
K, let me know if you get that working. I can test it out on your theme if you'd like, is [This Theme](http://themeforest.net/item/wp-pro-real-estate-7-responsive-wordpress-theme/12473778) the one you're working on?. :smile:

**Comment by contempoinc** [comment]
Yup, that's the one would be awesome if you could!

On Thursday, September 3, 2015, Webcreations907 notifications@github.com
wrote:

> K, let me know if you get that working. I can test it out on your theme if
> you'd like, is This Theme
> http://themeforest.net/item/wp-pro-real-estate-7-responsive-wordpress-theme/12473778
> the one you're working on? I can pickup a license if need be. [image:
> :smile:]
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/Webcreations907/WBC-Importer-extension/issues/39#issuecomment-137519235
> .

## 

Cheers,

Chris Robinson
www.contempoinc.com
twitter.com/contempoinc

**Comment by Webcreations907** [comment]
Seems to be working after replacing those files.
![vacation-import](https://cloud.githubusercontent.com/assets/8421576/9666212/476b02be-5221-11e5-897c-7381a50b785e.png)
![landing-import](https://cloud.githubusercontent.com/assets/8421576/9666214/49df9e7e-5221-11e5-86fe-59a766b45ec0.png)

**Comment by contempoinc** [comment]
Odd, I'll give it another shot prolly missed something or my browser is
caching hard or something.

On Thursday, September 3, 2015, Webcreations907 notifications@github.com
wrote:

> Seems to be working after replacing those files.
> [image: vacation-import]
> https://cloud.githubusercontent.com/assets/8421576/9666212/476b02be-5221-11e5-897c-7381a50b785e.png
> [image: landing-import]
> https://cloud.githubusercontent.com/assets/8421576/9666214/49df9e7e-5221-11e5-86fe-59a766b45ec0.png
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/Webcreations907/WBC-Importer-extension/issues/39#issuecomment-137527139
> .

## 

Cheers,

Chris Robinson
www.contempoinc.com
twitter.com/contempoinc

**Comment by Webcreations907** [comment]
Well hope that works out for you, kinda liking the progress bar there now so hope can get that figured out.. :)

**Comment by contempoinc** [comment]
Whenever I do a clone I keep getting master, I've tried git clone -b develop https://github.com/Webcreations907/WBC-Importer-extension.git with no luck. That's the correct way to grab the develop branch right?

**Comment by contempoinc** [comment]
Never mind got it working! http://cl.ly/image/0j030w3z2l3u

**Comment by contempoinc** [comment]
Ok, so I'm seeing this sometimes when importing http://cl.ly/image/1q1o0z151T0C is that due to server limits? Got the same thing on two different servers, probably php.ini memory?

**Comment by Webcreations907** [comment]
Great, glad you got that working. 

With the size of your import, mostly because of the images you may have to have users increase the max_execution_time. 

I'll be pushing some more changes here shortly to the dev branch, mainly going to change the ajax method for progress to GET.

Other than that, does that progress bar seem to be working out ok of you and your users?

**Comment by contempoinc** [comment]
Ok, yeah that's what I was thinking it is. Yeah, the progress bar is
working great, they're liking It much more since they can see where it's
at, rather than guessing. Thanks again man!

On Friday, September 4, 2015, Webcreations907 notifications@github.com
wrote:

> Great, glad you got that working.
> 
> With the size of your import, mostly because of the images you may have to
> have users increase the max_execution_time.
> 
> I'll be pushing some more changes here shortly to the dev branch, mainly
> going to change the ajax method for progress to GET.
> 
> Other than that, does that progress bar seem to be working out ok of you
> and your users?
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/Webcreations907/WBC-Importer-extension/issues/39#issuecomment-137858135
> .

## 

Cheers,

Chris Robinson
www.contempoinc.com
twitter.com/contempoinc

**Comment by Webcreations907** [comment]
No problem.

I'm almost done with that next update for the dev branch which I'll put set_time_limit() in there which will hopefully work for most server setups, the actual WP_importer uses it, but it seems to be getting skipped since it's being called differently.

So when I get that pushed, you may want to test it out then include it in your next theme update. Hopefully have that pushed up in 10-20 minutes.

**Comment by Webcreations907** [comment]
Develop branch is updated now.

Any issues just let me know

Thanks

**Comment by contempoinc** [comment]
Awesome, I'll give that a test

On Friday, September 4, 2015, Webcreations907 notifications@github.com
wrote:

> Develop branch is updated now.
> 
> Any issues just let me know
> 
> Thanks
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/Webcreations907/WBC-Importer-extension/issues/39#issuecomment-137875870
> .

## 

Cheers,

Chris Robinson
www.contempoinc.com
twitter.com/contempoinc

**Comment by contempoinc** [comment]
It'll still time out on some servers, looks like set_time_limit() didn't work. There's got a be a way so they don't have to manually up the limit in php.ini.

**Comment by Webcreations907** [comment]
I checked and it seems it's getting set higher, some servers/host providers may have it disabled though in that case they'd have to contact host or try the php.ini/.htaccess methods.

You know if they are timing out if doing the regular WP import option?

**Comment by contempoinc** [comment]
Times out using the normal importer as well.

Cheers,

Chris Robinson
www.contempoinc.com
twitter.com/contempoinc

**Comment by Webcreations907** [comment]
For now think you'll have to have them up the server settings if it's timing out with that as well, probably because of the image quality/quantity. 

I'm thinking of making up a different import process that would run in the background allowing users to move away from the import page and the import will continue and notify theme once complete. 

Also I made another change/push to the dev branch which reloads the theme options panel after import, so the theme options get updated in the panel. Because if they click save changes after import, then the imported theme options get overwritten with the default values if they didn't reload the page manually. So this should fix that issue, which was brought up in issue #36

Thanks :smile:

**Comment by vburlak** [comment]
@Webcreations907 thx a lot for progress bar feature.
Actually I came to ask whether there is a possibility to add action that reloads the theme options panel after import.
It's beautiful. Everything on develop branch. I will test it from develop branch

**Comment by Webcreations907** [comment]
Thanks @vburlak
That reload options panel after import should be in the develop branch as well, not sure if you seen that from my previous reply above.

**Comment by vburlak** [comment]
@Webcreations907 completely tested develop branch. 
Progress bar and reload options panel action works like a magic.

**Comment by cuocsongso** [comment]
Hello,

I am very interested in the Progress Bar, you can please send me the code.

My mail : huypdsoftware@gmail.com

Thank you very much!

**Comment by Webcreations907** [comment]
Progress bar feature and panel reload are now merged into main master files, so you can grab that. 😄
