### ISSUE TITLE
Export menus

### ISSUE THREAD

**Issue by grosscorporation** [Webcreations907/WBC-Importer-extension#4]
I am trying to export my menus with locations,
help with:

Primary (menu) Primary Menu (menu location)

anyone?

**Comment by Webcreations907** [comment]
Hello Zeal,

check out [This Block Of Code](https://github.com/Webcreations907/WBC-Importer-extension/blob/master/example-functions.php#L238-L257) that is in the `example-functions.php` on how to set your menus. 

You only need the name of the menu you want to set as primary. 

:smile:

**Comment by goranefbl** [comment]
In my case name of menu in export file is Main Menu, so code is:

` $top_menu = get_term_by( 'name', 'Main Menu', 'nav_menu' ); `

**Comment by grosscorporation** [comment]
wow! thanks Web

**Comment by Webcreations907** [comment]
No problem :)
