### ISSUE TITLE
skip content error and import widgets

### ISSUE THREAD

**Issue by kanawanzx** [Webcreations907/WBC-Importer-extension#41]
im import 1 file content and 1 file widgets. but import content it have error and won't import widget. i don't want this. i want import content (error or not error) then import widget or any file. how to do it

**Comment by Webcreations907** [comment]
Hello,

What error are you getting?

**Comment by kanawanzx** [comment]
my internet is slow... then not import complete.. i wana if  import content file not complete (error).it still works , then it import widget file ! do you know what i mean. sory my  english so bad

**Comment by Webcreations907** [comment]
Shouldn't be a issue unless you have lots of images with large file sizes being imported.

Could be server/hosting issue as well depending on size of the content you're importing.

**Comment by kanawanzx** [comment]
hello.
this is my problem . because my user in everywhere. i wanna skip import error of content.xml and import widget or slider .
sorry about my english,
