### ISSUE TITLE
Large Attachment Imports/Downloads?

### ISSUE THREAD

**Issue by contempoinc** [Webcreations907/WBC-Importer-extension#42]
I think you mentioned in a previous ticket you were working on something to break up the import or attachment downloads for large imports? Reason is I've had quite a few buyers like 10% have issues with the import since there's a bunch of large images, they've even upped server timeout and memory limits to no avail, guessing they're on low end shared hosting. Is there anyway to break up the import, or make it work with large image attachments?

**Comment by Webcreations907** [comment]
Hello,

Yeah I mentioned in other post about making the importer work in the background, just haven't had a chance to get that going as I'm trying to finish up a theme and some other projects. 

Not sure if the issues are with the timing out, or the file size for those you're having issues with. Are you able to check or have them check the server error log?

**Comment by contempoinc** [comment]
No worries man, whats odd is I've had them raise their server timeout limits and memory and the issue is still there so maybe its the file size? Getting server logs would be near impossible to explain or try to get, dealing with non-tech people.

**Comment by Webcreations907** [comment]
Do you know off hand the largest size image you have that's being imported?

**Comment by contempoinc** [comment]
I would say 1MB maybe 2MB max

Cheers,

Chris Robinson
www.contempoinc.com
twitter.com/contempoinc

**Comment by Webcreations907** [comment]
Doesn't seem that bad, but guess several could add up pretty quickly. Have you tried increasing all the below?
- max_execution_time
- memory_limit
- post_max_size
- upload_max_filesize
