### ISSUE TITLE
fetching content.xml from parent folder.

### ISSUE THREAD

**Issue by templatation** [Webcreations907/WBC-Importer-extension#43]
Hi,

First of all thanks for sharing this awesome piece of work.
I have one question.

In my theme, I plan to have multiple demos, but content.xml is same for all of them. So say I have 10 demos, and each share same context.xml file 10 times. So the file size of theme go up. (which inturn creates issues on shared hosting)

So is there a way that importer fetches the content.xml file from the 'demo-data' folder instead of its child directories. Same xml for all imports.
I could hack the code of extension, but I am looking your suggestion to do it in such a way so that I can update the extension in future easily without affecting my hack.

**Comment by Webcreations907** [comment]
Hello,
I'll add some filters in the next push for that so you can override the file path for content.xml, widgets, and theme options.

I'll try to get that done here in a bit.

**Comment by templatation** [comment]
Hi,

Sounds good. Thanks.

**Comment by Webcreations907** [comment]
Just added those filters to the [Develop Branch](https://github.com/Webcreations907/WBC-Importer-extension/tree/develop), so you can test that out. 

You can use something like the below to change the file path for the content.xml file.
The below replaces the content file if it's one of the demos in the provided array, add as needed. Make sure the names in the array are your demo folder names.

``` php
if(!function_exists('example_content_file')){
    /**
     * Change the content file location depending on demo
     * @param  (string) $location      full path to content file being passed
     * @param  (array)  $active_import Current active import info
     * @return (string)                full path to content file.
     */
    function example_content_file( $location, $active_import){
        reset( $active_import );
        $current_key = key( $active_import );

        //If it's one of these demo's currently being imported
        $wbc_content_replace = array('demo2', 'demo3');

        if( isset( $active_import[$current_key]['directory'] ) && in_array( $active_import[$current_key]['directory'], $wbc_content_replace ) ){

            //Give new location of content file. Note: Use path not URL
            $new_location = get_template_directory().'/path_to_your_content_file.xml';

            if ( !empty( $new_location ) && is_file( $new_location ) ) {
                return $new_location;
            }
        }

        return $location;
    }
    add_filter( 'wbc_importer_content_file_location', 'example_content_file', 10, 2 );
}
```

Use same type of function like above if you want to override widgets, or theme options file.

``` php
//For theme options file
add_filter( 'wbc_importer_options_file_location', 'your_function', 10, 2 );

//For widgets file
add_filter( 'wbc_importer_widget_file_location', 'your_function', 10, 2 );
```

**Comment by templatation** [comment]
Thanks alot :)

**Comment by templatation** [comment]
Hi,

I tried this method, and it works totally fine on my localhost.
But when I try it on my host ( wpengine ) it throws the error "something went wrong" popup. I tried for hours to sort it out but no avail.
Tried clearning cache, resetting file permission, echo'ed file name(to verify it exists) , as per my findings,  if ( !empty( $new_location ) && is_file( $new_location ) ) this return false on remote, no matter what. (however file path is correct and file exists)

Any valuable suggestions ?

**Comment by Webcreations907** [comment]
Hello,

Few things below. 

1- Did you try to echo `$new_location` before that check to see if the file path is correct? 

2- Do you have in special characters in your filename/folder path

3- When you say remote, are you trying to load the file from a different server?

**Comment by templatation** [comment]
Hi,

1) Yes, I did, and it echo'ed full path to file and its correct.
2) No, there are no special chars.
3) No, not different server, its just ../../ location.

However, Now I created a plugin for this extension instead, and not using this filter for now.
