### ISSUE TITLE
Set menu, import revolution slider, and set home page.

### ISSUE THREAD

**Issue by nicolagaldiolo** [Webcreations907/WBC-Importer-extension#44]
Hello, I apologize in advance for my poor English.

I installed the wbc_importer library inside the redux-extensions> extensions root and I followed all steps from 1 to 6 and it all works fine. :-)

Now I want to import RevSlider Set Menus, and Set Home Page ... I saw the file functions.php example-but I can not figure out which files should I put these functions ... I apologize but several hours I try to implement these functions but without success. 

Can you please help me figure out how to implement these functions properly? 
Thank you ... I'm sorry for the trouble.

Nicola Galdiolo.

**Comment by Webcreations907** [comment]
Hello,

If you look in the example-functions.php file, at the bottom there is a example function on how to set menus, homepage, and import rev slider. 

You'd just place that function in your functions.php file, or where ever you have your admin functions at.

**Comment by nicolagaldiolo** [comment]
Thanks a lot, it works perfectly! You can close the issue!

**Comment by pareshsojitra** [comment]
Hi,

It's not importing multiple sliders, can you help me in this ?

it imports only one slider

if ( class_exists( 'RevSlider' ) ) {

```
        //If it's demo3 or demo5
        $wbc_sliders_array = array(
            'Demo' => 'home.zip', // Set slider zip name
            'Demo' => 'shop.zip', // Set slider zip name
        );

        if ( isset( $demo_active_import[$current_key]['directory'] ) && !empty( $demo_active_import[$current_key]['directory'] ) && array_key_exists( $demo_active_import[$current_key]['directory'], $wbc_sliders_array ) ) {
            $wbc_slider_import = $wbc_sliders_array[$demo_active_import[$current_key]['directory']];

            if ( file_exists( $demo_directory_path.$wbc_slider_import ) ) {
                $slider = new RevSlider();
                $slider->importSliderFromPost( true, true, $demo_directory_path.$wbc_slider_import );
            }
        }
    }
```

**Comment by Webcreations907** [comment]
@smpdesignmedia Sorry for the delay, you'd just need to loop over the sliders, check out the issue below which has an example for multiple slider imports.

https://github.com/Webcreations907/WBC-Importer-extension/issues/15
