### ISSUE TITLE
Redux Panel is not updated on Import unless Page is Refresh

### ISSUE THREAD

**Issue by emorling** [Webcreations907/WBC-Importer-extension#47]
This is what happens:
1. Import demo including Redux data
2. Redux panels still show old data. The frontend indeed shows the fresh imported data

To re-populate Redux with the correct values I assume that the import function must force a page refresh? Is this being fixed?

**Comment by novalex** [comment]
I had the same issue, fixed it for now by adding

``` javascript
window.onbeforeunload = null; // Disable the unsaved changes alert
location.reload();
```

in field_wbc_importer.js after line 67.

**Comment by vburlak** [comment]
@emorling look at the [develop branch](https://github.com/Webcreations907/WBC-Importer-extension/tree/develop). Here is a solution e74f0315b258e156ceb7b617514c66d82e7351d1
