### ISSUE TITLE
Conflict with wordpress importer plugin from wordpress

### ISSUE THREAD

**Issue by goranefbl** [Webcreations907/WBC-Importer-extension#5]
There is issue when you install native wordpress import plugin, this is error that is showing:

![untitled](https://cloud.githubusercontent.com/assets/1670309/6426268/1f62b552-bf53-11e4-9b07-4bfa93b99757.png)

**Comment by Webcreations907** [comment]
Hey there,

I did a push back on Feb 3 that should of fixed that issue. Try updating your files for the wbc_importer to the latest/current and see if that fixes for you.

:)

**Comment by goranefbl** [comment]
awesome! :)
