### ISSUE TITLE
[Feature Request] - Add checkbox options on Import Data screen for select which data will be imported

### ISSUE THREAD

**Issue by vburlak** [Webcreations907/WBC-Importer-extension#52]
Hi, @Webcreations907 

I'm think it will be great to have ability to check, which demo data will be imported after clicking Import Demo button.
Now we have ability to import
- content.xml(posts + pages + comments + menus data)
- theme options
- widgets
- menus
- revolution slider
- and setup home page

For example, user(customer) want to import only:
- pages
- theme options
- menus
- revolution slider
- and setup home pages
  and exclude from import:
- posts
- comments
- and widgets.

Any advice about starting point to implement this feature?

**Comment by Webcreations907** [comment]
Hello,
Will keep this in mind for when I get some time, ideally I'd like to re-write the whole thing but depends on time and projects.

**Comment by Webcreations907** [comment]
@vburlak I added a feature request topic if you'd like to add there #76 

Thanks
