### ISSUE TITLE
WBC Importer not importing layer slider with redux

### ISSUE THREAD

**Issue by mrgurdeep** [Webcreations907/WBC-Importer-extension#53]
Hi

WPC imprter is an awesome extension for redux but unfortunately I am not able to import the LAyer sliders in my theme.

Slider revolution works just fine.Can you help with the Layer Slider issue please.

Thanks

**Comment by Webcreations907** [comment]
Hello,

I haven't spent much time with layer slider, when I get a change I'll take a look at their import process and see if it's possible.
