### ISSUE TITLE
Revolution Slider

### ISSUE THREAD

**Issue by Businezz99** [Webcreations907/WBC-Importer-extension#60]
Hi, i can not set revolution slider to be imported. I try to add example code to functions.php and i try also i add same code at extension_wbc_importer.php but doesn't work. Everything else it works, just sliders can not be imported.

**Comment by Webcreations907** [comment]
Hello,

What code are you using for the slider importing?

**Comment by Businezz99** [comment]
Hi, same code like from example-functions.php
But I paste that code at theme functions with slider locatio, which is in demo-files and doesn't work. Also I add that code in almost all files from wbc_importer folder, just in case if gonna work.

**Comment by Businezz99** [comment]
And radiux framework.

**Comment by Webcreations907** [comment]
Hopefully you got this worked out, if not just let me know.

Thanks
