### ISSUE TITLE
There was an error importing demo content message!

### ISSUE THREAD

**Issue by hamdan-mahran** [Webcreations907/WBC-Importer-extension#61]
Hi,

Thank you so much for this awesome plugin :) 
After i click on import demo button i get the message that showing in the attachment!
i get this message ( There was an error importing demo content ) 

Also i using XAMPP on my localhost
WP Memory Limit ========> 256 MB
PHP Time Limit  =========> 900

![error-message](https://cloud.githubusercontent.com/assets/8728448/13194133/0f14c194-d790-11e5-8feb-872019b8ebcb.jpg)

Thanks!

**Comment by Webcreations907** [comment]
Hello,
Are you importing a larger amount of images that are high quality?

**Comment by hamdan-mahran** [comment]
Hello @Webcreations907 

Thank you so much to reply to my question :)

Yes unfortunately, the xml file will import larger amount of images, it's about 150MB :(

**Comment by Webcreations907** [comment]
Sorry for the delay back, hopefully you got this figured out. Doesn't import large images that well as it just uses the WordPress Importer to import those.
