### ISSUE TITLE
Replace file_get_contents, fopen, fclose with WP_filesystem

### ISSUE THREAD

**Issue by rafalborowski** [Webcreations907/WBC-Importer-extension#62]
So after successfully implementing this (as I thought) I went back to Theme Check to see if everything is nice and clean and as it turns out it freaked out about `file_get_contents`, `fopen` and `fclose`. Now I know there's nothing wrong with those especially that they are used for read but nevertheless I wanted to get rid of those pesky warnings.

So I've tried to get the data in a different way like so

```
  function get_local_file_contents( $file ) {
      ob_start();
      include $file;
      $contents = ob_get_clean();

      return $contents;
  }
```

and then in place of `file_get_contents( $file );` just call the function above. Seems to work fine. Anyway I still have some issues on converting the `fopen`, `fclose` to WP_filesystem. Any suggestions?

Or could you share how to implement this PROPERLY as a plugin? Or is it just as simple as prefix the extension-init with comments so it's visible as plugin and pop your loader with it and call it a day?
Because I have it working, but as said just by taking all files (including demo data) into a plugin and then atfer-setup (for rev, menus etc.) included in functions.php. As said it works, but including demo files in plugin seems off to me... any advice?

**Comment by Delpierooo** [comment]
Having the same issue.  A replacement for thoose required or making everything a plugin. Any solution?

**Comment by elusivethemes** [comment]
I'm having the same issue, my themeforest theme is being rejected just for this. Any ideas ?

**Comment by rafalborowski** [comment]
@ukscotth Sure. Just pack it up as a plugin, throw it into TGM and call it a day :)

**Comment by elusivethemes** [comment]
Sorry for being stupid but how do I pack it up as a plugin because it has to go in the extensions folder of redux doesnt it ?

**Comment by rafalborowski** [comment]
Make the extenstion.init file as a plugin (not gonna explain the basics here), then just have the proper folder structure (init in plugin root folder, then extenstions/wbc_importer etc.) and that should be enough. To pack it with a theme include it via TGM (as per TF submission requirements) and make it install after Redux on theme install. 
If you are using it to also set up menus, set pages, install Rev Slider etc. then also include the "after setup" file in your functions.php but make sure it's included after Redux init.

**Comment by elusivethemes** [comment]
Thanks a lot, il give it a try :)

**Comment by elusivethemes** [comment]
Installed Redux and The importer both as plugins but now im getting this when trying to import the demo data : Fatal error:  Call to undefined function WP_Http() in .............

Any ideas ?

**Comment by elusivethemes** [comment]
And if i embed redux and use this as a plugin i get this : Fatal error: Class 'Redux' not found 

:(

**Comment by rafalborowski** [comment]
I just submitted like 4 days ago a working version. It's hard for me to debug from conversation. The Redux class missing is wired. You should have the Redux as a plugin anyway and then your config as an "embed" in fn.php overwriting redux. There is a lot of info online that it does not play nice with WP hooks (as it inits before) so it needs sometimes to be initialized before or sometimes after some functions. Maybe try playing with that? I have it setup like that:
1. Redux as plugin
2. Redux config/options as overweire in functions.php
3. WBS as plugin (as described above)
4. after-demo-seup.php included to run after redux config/options

Works like a charm. Anyway It's not that I don't want to help etc. but it's not a conversation for this thread.

**Comment by contempoinc** [comment]
@rafalborowski Could you share the code for WBC as a plugin and how you've setup your after-demo-setup.php, I'm running into the same issues with Themeforest & Theme Check its annoying as hell. Thanks in advance!

**Comment by contempoinc** [comment]
@rafalborowski Nevermind, was way simpler than I thought — got it!

**Comment by relstudiosnx** [comment]
@contempoinc can you please share me how you embed as plugin ?
