### ISSUE TITLE
Problem with Theme Check

### ISSUE THREAD

**Issue by mstoic** [Webcreations907/WBC-Importer-extension#64]
I am trying to publish a theme to ThemeForest, but they are soft rejecting it because Theme Check displays many errors when I include this extension. Any solution for that?

**Comment by Vishal-Deshpande** [comment]
@Webcreations907 Can you advice on, how to use wbc importer as standalone wp plugin? So that we can avoid TF soft rejection.

**Comment by simrandeep** [comment]
My theme is also soft rejected for including it in my theme. Any solution?

**Comment by Webcreations907** [comment]
I just replied to another topic #68 about that, maybe will help for your needs as well.

**Comment by simrandeep** [comment]
But you didn't mention if issues are fixed or not

**Comment by pixeltag** [comment]
i have same Problem , when i check my theme , it need to use WP_filesystem  instead of fopen , fclose , etc  in parser.php file . any ideas ?
thanks

**Comment by manchumahara** [comment]
@pixeltag   the parse method of parser.php file may show this error, replace the method with this https://gist.github.com/manchumahara/9627b6de7d8f0aa66bcb48e4418ed868 as work around,

delete ofpen and fclose methods as they are not needed

**Comment by Webcreations907** [comment]
Hopefully you got this figured out by now, sorry for the delay. 

If not just let me know.

Thanks
