### ISSUE TITLE
Demo Data from external URL 

### ISSUE THREAD

**Issue by NabilLahssine** [Webcreations907/WBC-Importer-extension#65]
Hi thanks for the great extension it's really helpful. I'm wondering if it's possible to have the demo files hosted on external server and not on local directory if yes please guide me on how to do that.

Thanks.

**Comment by Basilakis** [comment]
Hey,

Is there a solution on that one?
It does look as an amazing idea

**Comment by Webcreations907** [comment]
Hello,

Currently not a feature, but feel free to add to #76 for feature request.

Thanks

**Comment by NabilLahssine** [comment]
Thank you for your answer (even if it's a 9 month late one!)
I have already developed my own solution,

Best of luck

**Comment by baljka17** [comment]
@NabilLahssine Hi there,

Could you share me your solution/updates with me for external server resources importing?

Thanks

**Comment by xy440** [comment]
Still need this but no luck yet?

**Comment by xy440** [comment]
> Thank you for your answer (even if it's a 9 month late one!)
> I have already developed my own solution,
> 
> Best of luck

Could you please share your solution.
