### ISSUE TITLE
Importer stops after importing posts

### ISSUE THREAD

**Issue by Johnnychaos** [Webcreations907/WBC-Importer-extension#66]
When I run importer it stuck in the midway and spinner is running.
I can check that images are uploaded (they are lightweight placeholders) as well as all posts and pages are imported.
Theme options, widgets and menu are not.
When I refresh the page, and check "reimport" is imports the widgets, but still without theme options.

From error log: 

```
FastCGI: comm with server "/etc/www/php/fpm/chart-php70" aborted: idle timeout (310 sec), referer: http://apartment-wp.chart.civ.pl/test2/wp-admin/admin.php?page=apartment_wp&tab=1
FastCGI: incomplete headers (0 bytes) received from server "/etc/www/php/fpm/chart-php70", referer: http://apartment-wp.chart.civ.pl/test2/wp-admin/admin.php?page=apartment_wp&tab=1
```

**Comment by Webcreations907** [comment]
Hello,

Are you using PHP7? If so it's not updated for that version yet.

**Comment by Johnnychaos** [comment]
Yes, I am. Will it be updated? Do you have some time frame?
Regards, Jan

**Comment by ewtstudio** [comment]
Hi,
I have not php7. How can I solve this issue? Any idea, please. Thank you & Regards,

**Comment by Webcreations907** [comment]
Hoping you got this working, if not just let me know.

Thanks
