### ISSUE TITLE
Installing as a plugin ? 

### ISSUE THREAD

**Issue by BurakParsAydin** [Webcreations907/WBC-Importer-extension#68]
Hi, 

The extension is great. It saves time. However can i use this extention as WP plugin? If so, how ? 

Thank you!

**Comment by Basilakis** [comment]
That sounds the best for me, as a Demo Installer.
Is it possible?

**Comment by simrandeep** [comment]
I also want to know if I can supply it as a plugin with my themes.

**Comment by Basilakis** [comment]
Any reply here? Can we get a clue please @Webcreations907

**Comment by Webcreations907** [comment]
Hello,

Been very busy so hard to get in here at times. You can load your extensions from theme or plugin, you just need to change the location of your extension directory for Redux to load them from see [Redux Extension Loader](https://github.com/reduxframework/redux-extensions-loader) for more info on loading extensions from elsewhere.

**Comment by Basilakis** [comment]
Why closing, noone managed to do it :-)

**Comment by Webcreations907** [comment]
This is a old topic, trying to close out the ones that haven't been active in hopes it was figured out already.

If you use the [extension loader](https://github.com/reduxframework/redux-extensions-loader/blob/master/loader.php) linked above as well in a plugin then it will load your extensions that you have in the plugin, you'd just place the extensions in a folder called `extensions` within your plugin.
