### ISSUE TITLE
Slider, Menu, Home

### ISSUE THREAD

**Issue by trungjayce** [Webcreations907/WBC-Importer-extension#69]
Hi
I've included in the example-functions.php functions.php. But when the data import is finished it is still no Revolution Slider, config menu, config home page

Thank you!
![1](https://cloud.githubusercontent.com/assets/20389580/16905454/5bc43bae-4cd0-11e6-84dd-f7a60569e049.png)

**Comment by Webcreations907** [comment]
What version of PHP are you currently using? I noticed this issue when I was using PHP 7 but below was fine.

**Comment by jeni1616** [comment]
i think for php 7 we can apply this solution : https://wordpress.org/support/topic/menu-not-imported-in-php-version-708/ , i think it's working for me :)
