### ISSUE TITLE
admin-ajax.php 500 (Internal Server Error)

### ISSUE THREAD

**Issue by DoganAydemir** [Webcreations907/WBC-Importer-extension#7]
Hi;

I get the following error: 
![screen shot 2015-03-10 at 15 58 35](https://cloud.githubusercontent.com/assets/193340/6576526/73cd00e4-c740-11e4-9fd8-c5a2b896430a.png)

Can you help?

Thanks.

**Comment by DoganAydemir** [comment]
Php error logs:

"[10-Mar-2015 14:20:11 UTC] PHP Fatal error:  Allowed memory size of 41943040 bytes exhausted (tried to allocate 12288 bytes) in /Applications/MAMP/htdocs/chola22/wp-includes/class-wp-image-editor-imagick.php on line 135
"

**Comment by Webcreations907** [comment]
Hello,

Try increasing your memory limit and see if that resolves for you.

**Comment by Webcreations907** [comment]
Going to close this out assuming that worked for you, if you have any further issues just let me know. 

Thanks
