### ISSUE TITLE
Hi @Webcreations907 

### ISSUE THREAD

**Issue by zafarullahjoiya** [Webcreations907/WBC-Importer-extension#71]
This extension is super cool ... I really appreciate for your effort. I am using main mega menu plugin for menu presentation ... i want to import its demo file. how can i do that.is there any possibility if i create the demo file and place into demo1 folder like theme-options .... will it work for me?.
Main mega menu generate the txt file when we import the settings.

Thank you

**Comment by Webcreations907** [comment]
Hello,

Hopefully you got this figured out, if not just let me know and can try to take a look when I get a chance.

😄 Thanks
