### ISSUE TITLE
Using WP_Filesystem instead of file_get_contents & fopen to pass theme check?

### ISSUE THREAD

**Issue by contempoinc** [Webcreations907/WBC-Importer-extension#72]
Yo, is there any way to update this to use the WP_Filesystem instead of file_get_contents, fopen, & fclose so it'll pass theme check?

Screenshot https://cl.ly/34241o1s2a3J

**Comment by contempoinc** [comment]
Any word on this man? Themeforest is giving me hell over this, and I know the WordPress Importer plugin uses it still but they won't listen to me — its ridiculous.

**Comment by bibiangel1989** [comment]
Remove it, when you pass review, you can reinstall it & update your theme. This is my solution.

**Comment by contempoinc** [comment]
Naw, I actually turned the Redux Extensions into a custom plugin so there's no issues with theme check.

**Comment by bibiangel1989** [comment]
Yes, that is a good solution. :)

**Comment by pratik** [comment]
@contempoinc hey, can you share code of how you turned the extensions into a plugin ?

**Comment by Webcreations907** [comment]
Sorry I didn't get to ya sooner @contempoinc 

😞
