### ISSUE TITLE
Compatibility Note Concerning PHP 7

### ISSUE THREAD

**Issue by kenshiwara** [Webcreations907/WBC-Importer-extension#74]
**Topic:** Compatibility with PHP 7.0.13
**Tested on:** XAMPP -> PHP 7.0.13
**WordPress Version:** 4.7
**Redux Framework Plugin Version:** 3.6.3.2

```
FILE: wbc_importer/inc/importer/wordpress-importer.php
LINE 66: Use of deprecated PHP 4 style class constructor is not supported since PHP 7.
```

Thanks in advance for your reading my note.

**Comment by kenshiwara** [comment]
I have already placed a pull request at:
https://github.com/Webcreations907/WBC-Importer-extension/pull/75/files

All the best!

**Comment by Webcreations907** [comment]
Thanks 😄
