### ISSUE TITLE
Import several revolution sliders for one demo

### ISSUE THREAD

**Issue by temash** [Webcreations907/WBC-Importer-extension#77]
I have two revolution sliders in one demo. Can I import several sliders? How to do that? I used:
```
$wbc_sliders_array = array(
   'demo1' => 'slider1.zip',
   'demo1' => 'slider2.zip',
);
```
Not working, imported only latest 'slider2.zip' slider.
Thanks

**Comment by Webcreations907** [comment]
#15 If you were still looking for that 😄
