### ISSUE TITLE
Demo Importer tab not showing when redux is installed as plugin

### ISSUE THREAD

**Issue by goranefbl** [Webcreations907/WBC-Importer-extension#8]
Hey,

we added redux inside our theme that we sell in TF, this time we included this wonderfull extension. One customer reported demo importer tab not showing up, once i got into his site, i saw that he had redux installed as plugin too. Not sure if this is redux error, but everything else was working. So when u have redux in theme and and also activated as plugin, tab isnt showing.

**Comment by Webcreations907** [comment]
Hello,
I've tried to reproduce that and unable to, if I have it installed in theme with plugin active it still shows the demo importer.

Was the Redux plugin they had installed the default Redux plugin, or was it one customized for a theme/plugin?

Also are you on the latest version of Redux? 

Are you able to reproduce that issue with your set up/theme?

**Comment by goranefbl** [comment]
Hey Web,

As it was on clients side, he removed redux plugin, and now i cant test which version of redux it was. Lets close it up and if some other client brings it up again, i will let you know.

**Comment by Webcreations907** [comment]
Ok, thanks for keeping me posted. Let me know if you have further issues. 

I don't recall what version Redux made the update for multiple instances being ran at same time, so maybe they just had the older one installed.

:smile:
