### ISSUE TITLE
Fatal error with latest Redux

### ISSUE THREAD

**Issue by andrejarh** [Webcreations907/WBC-Importer-extension#85]
Hi,
I updated to the latest version of Redux and wbc_importer is returning a fatal error:

Fatal error: Uncaught Error: Call to a member function dirlist() on null in .../redux-extensions/extensions/wbc_importer/extension_wbc_importer.php:107 Stack trace: #0 .../redux-extensions/extensions/wbc_importer/extension_wbc_importer.php(149): ReduxFramework_extension_wbc_importer->demoFiles() #1 .../redux-extensions/extensions/wbc_importer/extension_wbc_importer.php(71): ReduxFramework_extension_wbc_importer->getImports() #2 .../redux-framework/inc/class.redux_api.php(71): ReduxFramework_extension_wbc_importer->__construct(Object(ReduxFramework)) #3 .../wordpress/wp-includes/class-wp-hook.php(286): Redux::loadExtensions(Object(ReduxFramework)) #4 /Use in .../redux-extensions/extensions/wbc_importer/extension_wbc_importer.php on line 107

**Comment by Ryu-k** [comment]
Hi, I have the same problem here.

Regards

**Comment by kprovance** [comment]
You no longer supporting this @Webcreations907 ?

**Comment by kprovance** [comment]
Just FYI - in case any else lurks - There was a problem with the Redux filesystem that did not turn up until now.  It's fixed on our side.  Any bugs or issues pertaining to this code, please keep here.  Thanks!

And @Webcreations907, seriously bro, have you abandoned this project?

**Comment by kprovance** [comment]
@andrejarh, you can close this ticket, since you opened.  :)

**Comment by Webcreations907** [comment]
Thanks @kprovance , I've been a bit behind with other projects, I looked into this a bit the other day and noticed the parent issue but didn't get a chance to post back here. 

Thanks for the fix, it seemed to resolve the issue. 

😄

**Comment by andrejarh** [comment]
Thank you @kprovance for taking time to look into it. 
Closing the issue.
